### ISSUE TITLE
running benchmark on x86

### ISSUE THREAD

**Issue by dipshirajput** [qdrant/vector-db-benchmark#108]
Hi , 
I am using `python3 -m run --engines *-m-16-* --datasets glove-*` for running the benchmark on x86. please let me know how much time it might take for the benchmark to complete ?

Thanks.

**Comment by KShivendu** [comment]
> please let me know how much time it might take for the benchmark to complete ?

That's depends heavily on your machine specs: CPU, RAM, etc. 

Closing this for now. Feel free to re-open if you have any more questions :)
