### ISSUE TITLE
Is this support to test pgvector

### ISSUE THREAD

**Issue by GreateFang** [qdrant/vector-db-benchmark#121]
I saw relative code in github but no pgvector data in the https://qdrant.tech/benchmarks/

**Comment by KShivendu** [comment]
Hi @GreateFang pgvector [PR was merged yesterday](https://github.com/qdrant/vector-db-benchmark/pull/98) so it's not included in https://qdrant.tech/benchmarks

It might be added in the next update. Lmk if you have any other questions =)
