### ISSUE TITLE
Automate testing of PRs across different engines

### ISSUE THREAD

**Issue by KShivendu** [qdrant/vector-db-benchmark#123]
Whenever we get external contributions, we have to test the repo ourselves to ensure that the code doesn't break. This can sometimes take a long time because it's done manually and we have limited bandwidth. 

Would be great if can automate it with Github actions (+our benchmarking servers if required)

**Comment by tellet-q** [comment]
Addressed in https://github.com/qdrant/vector-db-benchmark/pull/134
