### ISSUE TITLE
Progress bar for long running operations

### ISSUE THREAD

**Issue by joein** [qdrant/vector-db-benchmark#17]
We have no observability during loading or searching operations and have no sense whether everything is going as intended

However, it might be tough issue since it requires looking at the client's logs in real time

**Comment by KShivendu** [comment]
@joein I believe this is completed now. It shows progress during upload as well as search like this:
```
81235it [00:09, 10566.91it/s]
```

That's why I'm closing this. Feel free to re-open if you feel otherwise :)
