### ISSUE TITLE
Add PostgreSQL with pgvector to the benchmark

### ISSUE THREAD

**Issue by mmmaia** [qdrant/vector-db-benchmark#46]
Thank you for this benchmark! It adds a lot of value for those seeking a vector store.

I would greatly appreciate it if PostgreSQL with the [pgvector](https://github.com/pgvector/pgvector) extension could be included in the benchmark.

Using PostgreSQL is extremely convenient, so it would be beneficial to gain insights into how it performs in comparison to other database engines.

It would provide valuable information for users who want to make informed decisions when choosing a vector database for their projects.

**Comment by MochiXu** [comment]
you can see benchmark data in results directory @mmmaia

**Comment by KShivendu** [comment]
Closing since it was completed it #91
