### ISSUE TITLE
How to reproduce filtered search benchmark

### ISSUE THREAD

**Issue by alonre24** [qdrant/vector-db-benchmark#56]
Hi,
I didn't understand exactly what were the metrics in the [filtered search benchmark](https://qdrant.tech/benchmarks/#filtered-search-benchmark). How did you measure precision in these benchmarks? what are the differences between the "regular" and "filtered" search?

Also, is there a way of reproducing these benchmarks, as there is for the "pure" search benchmarks? Couldn't find the configuration files for the filtered benchmark.

I would appreciate any help, thanks!

**Comment by generall** [comment]
We used https://github.com/qdrant/ann-filtering-benchmark-datasets

**Comment by KShivendu** [comment]
Closing this since I believe the question has been answered. Feel free to ask any other questions related to Qdrant :)
