### ISSUE TITLE
How to embedding with batches?

### ISSUE THREAD

**Issue by DaiZack** [qdrant/vector-db-benchmark#70]
I am trying to do text embedding with the pipeline. How to improve the speed with batch setting (or parallel the data collection mapping)?
The current pipe is much slower than feed the sbert encoding with list of text directly.

![image](https://github.com/qdrant/vector-db-benchmark/assets/45176371/98467307-be22-4787-81c9-876c670d5f6c)

``` 
from towhee import AutoPipes
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')
texts = ['this is a document', 'this is another document', 'this is a third document']*1000

# with sbert directly
embeddings = model.encode(texts, batch_size=128, show_progress_bar=True)


# with towhee pipe
from towhee import pipe, ops
text_embedding = (pipe.input('text')
         .map('text', 'embedding', ops.sentence_embedding.transformers(model_name='all-MiniLM-L6-v2',))
         .output('text', 'embedding')
     )


res = text_embedding.batch(texts)
```

**Comment by KShivendu** [comment]
Hi @DaiZack, I think this question is related to Towhee more than Qdrant. It's better to ask in their community/repos :)
