### ISSUE TITLE
Benchmark Analysis with Various Datasets

### ISSUE THREAD

**Issue by harshakhmk** [qdrant/vector-db-benchmark#90]
Hi, I was trying to do benchmark testing for Qdrant for different datasets, however the script is not running for Mnist, SIFT, NYTimes
Are there any changes to be made to run for these datasets? If yes please mention those changes

**Comment by KShivendu** [comment]
Hi @harshakhmk, we support [these formats](https://github.com/qdrant/vector-db-benchmark/tree/master/dataset_reader). Any new dataset must be in either of those formats and then you just need to add it to `datasets.json`.

How are you downloading the datasets? Are you using something like the `datasets` library by HF?

**Comment by harshakhmk** [comment]
I have experimented with MNIST dataset https://www.kaggle.com/datasets/oddrationale/mnist-in-csv

**Comment by KShivendu** [comment]
Okay. You need to do some processing on the dataset and make it aligned with the formats I mentioned above. You can refer to my [implementation](https://github.com/qdrant/ann-filtering-benchmark-datasets/blob/master/generators%2Fdbpedia_openai_1M%2Fgenerate_dbpedia_openai_1M.py) for the OpenAI 1M embeddings dataset on HuggingFace. 

Also, it doesn't make sense to run it directly on MNIST image features. It's not a valid dataset for running any kind of search benchmarks.
